name: RSpec Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    env:
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: test
      RUBY_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CANVAS_URL: http://bcourses.test.instructure.com/
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Setup Database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: Download and install Code Climate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Run before-build command
      run: ./cc-test-reporter before-build
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    - name: Create Chrome data directory
      run: mkdir -p /tmp/chrome-data-rspec
    - name: Run RSpec Tests
      run: bundle exec rspec spec/ --tag ~skip --tag ~wip
      env:
        CHROME_DATA_DIR: /tmp/chrome-data-rspec
    - name: Run after-build command
      run: |
        ./cc-test-reporter after-build --exit-code $?
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 